<?php

// admin/master_medicines.php

require_once __DIR__ . '/../config/tenant_db.php';

require_once __DIR__ . '/../config/alerts.php';



$page_title = "Medicine Master";

$org_id     = (int)($_SESSION['org_id'] ?? 1);

$center_id  = (int)($_SESSION['center_id'] ?? 1);

$created_by = (int)($_SESSION['user_id'] ?? 0);

// ---------------------------------------------------------
// DEFAULT MEDICINE CATALOG (generic starter catalogue)
// Safe to run on every page load: inserts only missing combinations.
// This is not every medicine/brand worldwide; keep clinic-specific data editable.
// ---------------------------------------------------------
$defaultMedicines = [
['PARACETAMOL','PARACETAMOL','500 MG','TAB (TABLET)','ANALGESIC / ANTIPYRETIC'],
['PARACETAMOL','PARACETAMOL','650 MG','TAB (TABLET)','ANALGESIC / ANTIPYRETIC'],
['PARACETAMOL SYRUP','PARACETAMOL','125 MG/5 ML','SYRUP','ANALGESIC / ANTIPYRETIC'],
['IBUPROFEN','IBUPROFEN','200 MG','TAB (TABLET)','NSAID'],
['IBUPROFEN','IBUPROFEN','400 MG','TAB (TABLET)','NSAID'],
['DICLOFENAC','DICLOFENAC','50 MG','TAB (TABLET)','NSAID'],
['ACE CLOFENAC','ACECLOFENAC','100 MG','TAB (TABLET)','NSAID'],
['NAPROXEN','NAPROXEN','250 MG','TAB (TABLET)','NSAID'],
['ASPIRIN','ACETYLSALICYLIC ACID','75 MG','TAB (TABLET)','ANTIPLATELET'],
['CETIRIZINE','CETIRIZINE','10 MG','TAB (TABLET)','ANTIHISTAMINE'],
['LEVOCETIRIZINE','LEVOCETIRIZINE','5 MG','TAB (TABLET)','ANTIHISTAMINE'],
['FEXOFENADINE','FEXOFENADINE','120 MG','TAB (TABLET)','ANTIHISTAMINE'],
['LORATADINE','LORATADINE','10 MG','TAB (TABLET)','ANTIHISTAMINE'],
['MONTELUKAST','MONTELUKAST','10 MG','TAB (TABLET)','ANTIALlergic'],
['PANTOPRAZOLE','PANTOPRAZOLE','40 MG','TAB (TABLET)','GASTRO'],
['OMEPRAZOLE','OMEPRAZOLE','20 MG','CAP (CAPSULE)','GASTRO'],
['ESOMEPRAZOLE','ESOMEPRAZOLE','40 MG','TAB (TABLET)','GASTRO'],
['RABEPRAZOLE','RABEPRAZOLE','20 MG','TAB (TABLET)','GASTRO'],
['FAMOTIDINE','FAMOTIDINE','20 MG','TAB (TABLET)','GASTRO'],
['ONDANSETRON','ONDANSETRON','4 MG','TAB (TABLET)','ANTIEMETIC'],
['DOMPERIDONE','DOMPERIDONE','10 MG','TAB (TABLET)','GASTRO'],
['ORS','ORAL REHYDRATION SALTS','STANDARD','SACHET','REHYDRATION'],
['LACTULOSE','LACTULOSE','SOLUTION','SYRUP','LAXATIVE'],
['ISABGOL','PSYLLIUM HUSK','POWDER','POWDER','LAXATIVE'],
['AMOXICILLIN','AMOXICILLIN','500 MG','CAP (CAPSULE)','ANTIBIOTIC'],
['AMOXICILLIN CLAVULANATE','AMOXICILLIN + CLAVULANIC ACID','625 MG','TAB (TABLET)','ANTIBIOTIC'],
['AZITHROMYCIN','AZITHROMYCIN','250 MG','TAB (TABLET)','ANTIBIOTIC'],
['AZITHROMYCIN','AZITHROMYCIN','500 MG','TAB (TABLET)','ANTIBIOTIC'],
['CEFIXIME','CEFIXIME','200 MG','TAB (TABLET)','ANTIBIOTIC'],
['CEFUROXIME','CEFUROXIME','500 MG','TAB (TABLET)','ANTIBIOTIC'],
['DOXYCYCLINE','DOXYCYCLINE','100 MG','CAP (CAPSULE)','ANTIBIOTIC'],
['METRONIDAZOLE','METRONIDAZOLE','400 MG','TAB (TABLET)','ANTIMICROBIAL'],
['CIPROFLOXACIN','CIPROFLOXACIN','500 MG','TAB (TABLET)','ANTIBIOTIC'],
['LEVOFLOXACIN','LEVOFLOXACIN','500 MG','TAB (TABLET)','ANTIBIOTIC'],
['NITROFURANTOIN','NITROFURANTOIN','100 MG','CAP (CAPSULE)','ANTIBIOTIC'],
['FLUCONAZOLE','FLUCONAZOLE','150 MG','TAB (TABLET)','ANTIFUNGAL'],
['CLOTRIMAZOLE CREAM','CLOTRIMAZOLE','1%','CREAM','ANTIFUNGAL'],
['ACYCLOVIR','ACYCLOVIR','400 MG','TAB (TABLET)','ANTIVIRAL'],
['ALBENDAZOLE','ALBENDAZOLE','400 MG','TAB (TABLET)','ANTHELMINTIC'],
['METFORMIN','METFORMIN','500 MG','TAB (TABLET)','ANTIDIABETIC'],
['METFORMIN','METFORMIN','1000 MG','TAB (TABLET)','ANTIDIABETIC'],
['GLIMEPIRIDE','GLIMEPIRIDE','1 MG','TAB (TABLET)','ANTIDIABETIC'],
['GLIMEPIRIDE','GLIMEPIRIDE','2 MG','TAB (TABLET)','ANTIDIABETIC'],
['SITAGLIPTIN','SITAGLIPTIN','100 MG','TAB (TABLET)','ANTIDIABETIC'],
['EMPAGLIFLOZIN','EMPAGLIFLOZIN','10 MG','TAB (TABLET)','ANTIDIABETIC'],
['INSULIN REGULAR','INSULIN HUMAN','100 IU/ML','INJECTION','ANTIDIABETIC'],
['AMLODIPINE','AMLODIPINE','5 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['TELMISARTAN','TELMISARTAN','40 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['LOSARTAN','LOSARTAN','50 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['ENALAPRIL','ENALAPRIL','5 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['RAMIPRIL','RAMIPRIL','2.5 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['ATORVASTATIN','ATORVASTATIN','10 MG','TAB (TABLET)','LIPID LOWERING'],
['ATORVASTATIN','ATORVASTATIN','20 MG','TAB (TABLET)','LIPID LOWERING'],
['ROSUVASTATIN','ROSUVASTATIN','10 MG','TAB (TABLET)','LIPID LOWERING'],
['CLOPIDOGREL','CLOPIDOGREL','75 MG','TAB (TABLET)','ANTIPLATELET'],
['LEVOTHYROXINE','LEVOTHYROXINE','25 MCG','TAB (TABLET)','THYROID'],
['LEVOTHYROXINE','LEVOTHYROXINE','50 MCG','TAB (TABLET)','THYROID'],
['PREDNISOLONE','PREDNISOLONE','5 MG','TAB (TABLET)','CORTICOSTEROID'],
['HYDROCORTISONE CREAM','HYDROCORTISONE','1%','CREAM','DERMATOLOGY'],
['BETAMETHASONE CREAM','BETAMETHASONE','0.1%','CREAM','DERMATOLOGY'],
['CALAMINE LOTION','CALAMINE','LOTION','LOTION','DERMATOLOGY'],
['MUPIROCIN OINTMENT','MUPIROCIN','2%','OINTMENT','DERMATOLOGY'],
['SALBUTAMOL INHALER','SALBUTAMOL','100 MCG/PUFF','INHALER','RESPIRATORY'],
['BUDESONIDE INHALER','BUDESONIDE','200 MCG','INHALER','RESPIRATORY'],
['AMBROXOL SYRUP','AMBROXOL','SYRUP','SYRUP','RESPIRATORY'],
['DEXTROMETHORPHAN SYRUP','DEXTROMETHORPHAN','SYRUP','SYRUP','RESPIRATORY'],
['ACETYLCYSTEINE','ACETYLCYSTEINE','600 MG','TAB (TABLET)','RESPIRATORY'],
['VITAMIN C','ASCORBIC ACID','500 MG','TAB (TABLET)','VITAMIN'],
['VITAMIN D3','CHOLECALCIFEROL','60000 IU','CAP (CAPSULE)','VITAMIN'],
['CALCIUM + VITAMIN D3','CALCIUM + CHOLECALCIFEROL','TABLET','TAB (TABLET)','SUPPLEMENT'],
['FERROUS ASCORBATE + FOLIC ACID','IRON + FOLIC ACID','TABLET','TAB (TABLET)','SUPPLEMENT'],
['FOLIC ACID','FOLIC ACID','5 MG','TAB (TABLET)','VITAMIN'],
['CYANOCOBALAMIN','VITAMIN B12','500 MCG','TAB (TABLET)','VITAMIN'],
['ZINC SULPHATE','ZINC SULPHATE','20 MG','TAB (TABLET)','SUPPLEMENT'],
['MULTIVITAMIN','MULTIVITAMINS','TABLET','TAB (TABLET)','SUPPLEMENT'],
['THIAMINE','VITAMIN B1','100 MG','TAB (TABLET)','VITAMIN'],
['FUROSEMIDE','FUROSEMIDE','40 MG','TAB (TABLET)','DIURETIC'],
['SPIRONOLACTONE','SPIRONOLACTONE','25 MG','TAB (TABLET)','DIURETIC'],
['METOPROLOL','METOPROLOL','25 MG','TAB (TABLET)','CARDIAC'],
['PROPRANOLOL','PROPRANOLOL','10 MG','TAB (TABLET)','CARDIAC'],
['DIGOXIN','DIGOXIN','0.25 MG','TAB (TABLET)','CARDIAC'],
['TAMSULOSIN','TAMSULOSIN','0.4 MG','CAP (CAPSULE)','UROLOGY'],
['FINASTERIDE','FINASTERIDE','5 MG','TAB (TABLET)','UROLOGY'],
['TRANEXAMIC ACID','TRANEXAMIC ACID','500 MG','TAB (TABLET)','HEMOSTATIC'],
['MEFENAMIC ACID','MEFENAMIC ACID','500 MG','TAB (TABLET)','NSAID'],
['ETORICOXIB','ETORICOXIB','60 MG','TAB (TABLET)','NSAID'],
['TRAMADOL','TRAMADOL','50 MG','CAP (CAPSULE)','ANALGESIC'],
['LIDOCAINE INJECTION','LIDOCAINE','2%','INJECTION','LOCAL ANESTHETIC'],
['CEFTRIAXONE INJECTION','CEFTRIAXONE','1 G','INJECTION','ANTIBIOTIC'],
['DICLOFENAC INJECTION','DICLOFENAC','75 MG/3 ML','INJECTION','NSAID'],
['PANTOPRAZOLE INJECTION','PANTOPRAZOLE','40 MG','INJECTION','GASTRO'],
['ONDANSETRON INJECTION','ONDANSETRON','2 MG/ML','INJECTION','ANTIEMETIC'],
['NORMAL SALINE','SODIUM CHLORIDE','0.9%','INFUSION','IV FLUID'],
['DEXTROSE 5%','DEXTROSE','5%','INFUSION','IV FLUID'],
['RINGER LACTATE','COMPOUND SODIUM LACTATE','INFUSION','INFUSION','IV FLUID'],
['POVIDONE IODINE','POVIDONE IODINE','10%','SOLUTION','ANTISEPTIC'],
['CHLORHEXIDINE','CHLORHEXIDINE','SOLUTION','SOLUTION','ANTISEPTIC'],
['EYE LUBRICANT','CARBOXYMETHYLCELLULOSE','0.5%','DROPS','OPHTHALMIC'],
['MOXIFLOXACIN EYE DROPS','MOXIFLOXACIN','0.5%','DROPS','OPHTHALMIC'],
['EAR WAX DROPS','EAR WAX SOFTENER','DROPS','DROPS','OTIC'],
['XYLOMETAZOLINE NASAL DROPS','XYLOMETAZOLINE','0.1%','DROPS','NASAL'],
['LUBRICATING EYE OINTMENT','LUBRICANT','OINTMENT','OINTMENT','OPHTHALMIC'],
['OMNIPAQUE','IOHEXOL','300 MG I/ML','INJECTION','CONTRAST MEDIA'],

// Expanded generic catalogue: common primary-care, specialty and hospital medicines.
// These are catalogue entries only; no dose, frequency or duration is pre-assigned.
['ACETAMINOPHEN','PARACETAMOL','325 MG','TAB (TABLET)','ANALGESIC / ANTIPYRETIC'],
['NAPROXEN','NAPROXEN','500 MG','TAB (TABLET)','NSAID'],
['MELOXICAM','MELOXICAM','7.5 MG','TAB (TABLET)','NSAID'],
['PIROXICAM','PIROXICAM','20 MG','CAP (CAPSULE)','NSAID'],
['KETOROLAC','KETOROLAC','10 MG','TAB (TABLET)','NSAID'],
['ETODOLAC','ETODOLAC','400 MG','TAB (TABLET)','NSAID'],
['CELECOXIB','CELECOXIB','100 MG','CAP (CAPSULE)','NSAID'],
['ACEclofenac PARACETAMOL','ACECLOFENAC + PARACETAMOL','COMBINATION','TAB (TABLET)','ANALGESIC'],
['METHOCARBAMOL','METHOCARBAMOL','500 MG','TAB (TABLET)','MUSCLE RELAXANT'],
['TIZANIDINE','TIZANIDINE','2 MG','TAB (TABLET)','MUSCLE RELAXANT'],
['BACLOFEN','BACLOFEN','10 MG','TAB (TABLET)','MUSCLE RELAXANT'],
['GABAPENTIN','GABAPENTIN','300 MG','CAP (CAPSULE)','NEUROPATHIC PAIN'],
['PREGABALIN','PREGABALIN','75 MG','CAP (CAPSULE)','NEUROPATHIC PAIN'],
['AMITRIPTYLINE','AMITRIPTYLINE','10 MG','TAB (TABLET)','NEUROLOGY / PSYCHIATRY'],
['DULOXETINE','DULOXETINE','30 MG','CAP (CAPSULE)','NEUROLOGY / PSYCHIATRY'],
['SUMATRIPTAN','SUMATRIPTAN','50 MG','TAB (TABLET)','MIGRAINE'],
['FLUNARIZINE','FLUNARIZINE','10 MG','TAB (TABLET)','MIGRAINE'],
['BETAHISTINE','BETAHISTINE','16 MG','TAB (TABLET)','VERTIGO'],
['MECLIZINE','MECLIZINE','25 MG','TAB (TABLET)','VERTIGO / ANTIEMETIC'],
['METOCLOPRAMIDE','METOCLOPRAMIDE','10 MG','TAB (TABLET)','ANTIEMETIC'],
['PROCHLORPERAZINE','PROCHLORPERAZINE','5 MG','TAB (TABLET)','ANTIEMETIC'],
['DROTAVERINE','DROTAVERINE','80 MG','TAB (TABLET)','ANTISPASMODIC'],
['HYOSCINE BUTYLBROMIDE','HYOSCINE BUTYLBROMIDE','10 MG','TAB (TABLET)','ANTISPASMODIC'],
['SIMETHICONE','SIMETHICONE','80 MG','TAB (TABLET)','GASTRO'],
['ALUMINIUM MAGNESIUM ANTACID','ALUMINIUM HYDROXIDE + MAGNESIUM HYDROXIDE','SUSPENSION','SUSPENSION','ANTACID'],
['SUCRALFATE','SUCRALFATE','1 G','TAB (TABLET)','GASTRO'],
['BISMUTH SUBSALICYLATE','BISMUTH SUBSALICYLATE','SUSPENSION','SUSPENSION','GASTRO'],
['MESALAZINE','MESALAZINE','400 MG','TAB (TABLET)','GASTROENTEROLOGY'],
['RIFAXIMIN','RIFAXIMIN','550 MG','TAB (TABLET)','GASTROENTEROLOGY'],
['SENNA','SENNA','TABLET','TAB (TABLET)','LAXATIVE'],
['BISACODYL','BISACODYL','5 MG','TAB (TABLET)','LAXATIVE'],
['POLYETHYLENE GLYCOL','MACROGOL / PEG','POWDER','POWDER','LAXATIVE'],
['ZINC OXIDE CREAM','ZINC OXIDE','CREAM','CREAM','DERMATOLOGY'],
['LULICONAZOLE','LULICONAZOLE','1%','CREAM','ANTIFUNGAL'],
['TERBINAFINE','TERBINAFINE','250 MG','TAB (TABLET)','ANTIFUNGAL'],
['ITRACONAZOLE','ITRACONAZOLE','100 MG','CAP (CAPSULE)','ANTIFUNGAL'],
['KETOCONAZOLE SHAMPOO','KETOCONAZOLE','2%','SHAMPOO','DERMATOLOGY'],
['PERMETHRIN','PERMETHRIN','5%','CREAM','SCABICIDE'],
['BENZOYL PEROXIDE','BENZOYL PEROXIDE','2.5%','GEL','DERMATOLOGY'],
['ADAPALENE','ADAPALENE','0.1%','GEL','DERMATOLOGY'],
['TRETINOIN','TRETINOIN','0.025%','CREAM','DERMATOLOGY'],
['CLOBETASOL PROPIONATE','CLOBETASOL PROPIONATE','0.05%','CREAM','CORTICOSTEROID'],
['MOMETASONE','MOMETASONE FUROATE','0.1%','CREAM','CORTICOSTEROID'],
['FUSIDIC ACID','FUSIDIC ACID','2%','CREAM','TOPICAL ANTIBIOTIC'],
['SILVER SULFADIAZINE','SILVER SULFADIAZINE','1%','CREAM','WOUND CARE'],
['LIGNOCAINE GEL','LIDOCAINE','2%','GEL','LOCAL ANESTHETIC'],
['CHLORPHENIRAMINE','CHLORPHENIRAMINE','4 MG','TAB (TABLET)','ANTIHISTAMINE'],
['HYDROXYZINE','HYDROXYZINE','25 MG','TAB (TABLET)','ANTIHISTAMINE'],
['DESLORATADINE','DESLORATADINE','5 MG','TAB (TABLET)','ANTIHISTAMINE'],
['BILASTINE','BILASTINE','20 MG','TAB (TABLET)','ANTIHISTAMINE'],
['DEXAMETHASONE','DEXAMETHASONE','4 MG','TAB (TABLET)','CORTICOSTEROID'],
['METHYLPREDNISOLONE','METHYLPREDNISOLONE','4 MG','TAB (TABLET)','CORTICOSTEROID'],
['HYDROCORTISONE INJECTION','HYDROCORTISONE','100 MG','INJECTION','CORTICOSTEROID'],
['ADRENALINE INJECTION','EPINEPHRINE','1 MG/ML','INJECTION','EMERGENCY MEDICINE'],
['ATROPINE INJECTION','ATROPINE','0.6 MG/ML','INJECTION','EMERGENCY MEDICINE'],
['AMIODARONE','AMIODARONE','200 MG','TAB (TABLET)','CARDIAC'],
['DILTIAZEM','DILTIAZEM','30 MG','TAB (TABLET)','CARDIAC'],
['VERAPAMIL','VERAPAMIL','40 MG','TAB (TABLET)','CARDIAC'],
['BISOPROLOL','BISOPROLOL','5 MG','TAB (TABLET)','CARDIAC'],
['CARVEDILOL','CARVEDILOL','6.25 MG','TAB (TABLET)','CARDIAC'],
['NEBIVOLOL','NEBIVOLOL','5 MG','TAB (TABLET)','CARDIAC'],
['HYDROCHLOROTHIAZIDE','HYDROCHLOROTHIAZIDE','12.5 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['CHLORTHALIDONE','CHLORTHALIDONE','12.5 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['OLMESARTAN','OLMESARTAN','20 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['VALSARTAN','VALSARTAN','80 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['SACUBITRIL VALSARTAN','SACUBITRIL + VALSARTAN','COMBINATION','TAB (TABLET)','CARDIAC'],
['ISOSORBIDE MONONITRATE','ISOSORBIDE MONONITRATE','20 MG','TAB (TABLET)','CARDIAC'],
['NITROGLYCERIN','GLYCERYL TRINITRATE','0.5 MG','TAB (TABLET)','CARDIAC'],
['RANOLAZINE','RANOLAZINE','500 MG','TAB (TABLET)','CARDIAC'],
['EZETIMIBE','EZETIMIBE','10 MG','TAB (TABLET)','LIPID LOWERING'],
['FENOFIBRATE','FENOFIBRATE','160 MG','TAB (TABLET)','LIPID LOWERING'],
['APIXABAN','APIXABAN','5 MG','TAB (TABLET)','ANTICOAGULANT'],
['RIVAROXABAN','RIVAROXABAN','10 MG','TAB (TABLET)','ANTICOAGULANT'],
['WARFARIN','WARFARIN','2 MG','TAB (TABLET)','ANTICOAGULANT'],
['ENOXAPARIN','ENOXAPARIN','40 MG/0.4 ML','INJECTION','ANTICOAGULANT'],
['TICAGRELOR','TICAGRELOR','90 MG','TAB (TABLET)','ANTIPLATELET'],
['GLICLAZIDE','GLICLAZIDE','80 MG','TAB (TABLET)','ANTIDIABETIC'],
['VILDAGLIPTIN','VILDAGLIPTIN','50 MG','TAB (TABLET)','ANTIDIABETIC'],
['LINAGLIPTIN','LINAGLIPTIN','5 MG','TAB (TABLET)','ANTIDIABETIC'],
['DAPAGLIFLOZIN','DAPAGLIFLOZIN','10 MG','TAB (TABLET)','ANTIDIABETIC'],
['PIOGLITAZONE','PIOGLITAZONE','15 MG','TAB (TABLET)','ANTIDIABETIC'],
['GLYCLOPYRROLATE','GLYCOPYRROLATE','1 MG','TAB (TABLET)','OTHER'],
['GLUCAGON','GLUCAGON','1 MG','INJECTION','EMERGENCY MEDICINE'],
['L-THYROXINE','LEVOTHYROXINE','100 MCG','TAB (TABLET)','THYROID'],
['CARBIMAZOLE','CARBIMAZOLE','5 MG','TAB (TABLET)','THYROID'],
['PROPYLTHIOURACIL','PROPYLTHIOURACIL','50 MG','TAB (TABLET)','THYROID'],
['CALCITRIOL','CALCITRIOL','0.25 MCG','CAP (CAPSULE)','VITAMIN / MINERAL'],
['ALENDRONATE','ALENDRONIC ACID','70 MG','TAB (TABLET)','BONE HEALTH'],
['DENOSUMAB','DENOSUMAB','60 MG/ML','INJECTION','BONE HEALTH'],
['IRON SUCROSE','IRON SUCROSE','20 MG/ML','INJECTION','HAEMATINIC'],
['ERYTHROPOIETIN','EPOETIN ALFA','INJECTION','INJECTION','HAEMATINIC'],
['POTASSIUM CHLORIDE','POTASSIUM CHLORIDE','SOLUTION','SOLUTION','ELECTROLYTE'],
['MAGNESIUM SULPHATE','MAGNESIUM SULPHATE','INJECTION','INJECTION','ELECTROLYTE'],
['CALCIUM GLUCONATE','CALCIUM GLUCONATE','INJECTION','INJECTION','ELECTROLYTE'],
['THIAMINE INJECTION','THIAMINE','100 MG/ML','INJECTION','VITAMIN'],
['PYRIDOXINE','PYRIDOXINE','40 MG','TAB (TABLET)','VITAMIN'],
['BIOTIN','BIOTIN','5 MG','TAB (TABLET)','VITAMIN'],
['VITAMIN K','PHYTONADIONE','10 MG/ML','INJECTION','VITAMIN'],
['FOLINIC ACID','CALCIUM FOLINATE','15 MG','TAB (TABLET)','VITAMIN'],
['CEPHALEXIN','CEPHALEXIN','500 MG','CAP (CAPSULE)','ANTIBIOTIC'],
['CEFPODOXIME','CEFPODOXIME','200 MG','TAB (TABLET)','ANTIBIOTIC'],
['CEFIXIME SUSPENSION','CEFIXIME','100 MG/5 ML','SUSPENSION','ANTIBIOTIC'],
['AMIKACIN','AMIKACIN','500 MG/2 ML','INJECTION','ANTIBIOTIC'],
['GENTAMICIN','GENTAMICIN','40 MG/ML','INJECTION','ANTIBIOTIC'],
['PIPERACILLIN TAZOBACTAM','PIPERACILLIN + TAZOBACTAM','INJECTION','INJECTION','ANTIBIOTIC'],
['MEROPENEM','MEROPENEM','1 G','INJECTION','ANTIBIOTIC'],
['VANCOMYCIN','VANCOMYCIN','500 MG','INJECTION','ANTIBIOTIC'],
['LINEZOLID','LINEZOLID','600 MG','TAB (TABLET)','ANTIBIOTIC'],
['CLINDAMYCIN','CLINDAMYCIN','300 MG','CAP (CAPSULE)','ANTIBIOTIC'],
['CO-TRIMOXAZOLE','SULFAMETHOXAZOLE + TRIMETHOPRIM','COMBINATION','TAB (TABLET)','ANTIBIOTIC'],
['RIFAMPICIN','RIFAMPICIN','450 MG','TAB (TABLET)','ANTIMYCOBACTERIAL'],
['ISONIAZID','ISONIAZID','300 MG','TAB (TABLET)','ANTIMYCOBACTERIAL'],
['ETHAMBUTOL','ETHAMBUTOL','400 MG','TAB (TABLET)','ANTIMYCOBACTERIAL'],
['PYRAZINAMIDE','PYRAZINAMIDE','500 MG','TAB (TABLET)','ANTIMYCOBACTERIAL'],
['ARTEMETHER LUMEFANTRINE','ARTEMETHER + LUMEFANTRINE','COMBINATION','TAB (TABLET)','ANTIMALARIAL'],
['CHLOROQUINE','CHLOROQUINE','250 MG','TAB (TABLET)','ANTIMALARIAL'],
['OSELTAMIVIR','OSELTAMIVIR','75 MG','CAP (CAPSULE)','ANTIVIRAL'],
['VALACICLOVIR','VALACICLOVIR','500 MG','TAB (TABLET)','ANTIVIRAL'],
['TENOFOVIR','TENOFOVIR DISOPROXIL','300 MG','TAB (TABLET)','ANTIVIRAL'],
['LAMIVUDINE','LAMIVUDINE','100 MG','TAB (TABLET)','ANTIVIRAL'],
['EMTRICITABINE TENOFOVIR','EMTRICITABINE + TENOFOVIR','COMBINATION','TAB (TABLET)','ANTIVIRAL'],
['LEVETIRACETAM','LEVETIRACETAM','500 MG','TAB (TABLET)','ANTIEPILEPTIC'],
['SODIUM VALPROATE','SODIUM VALPROATE','500 MG','TAB (TABLET)','ANTIEPILEPTIC'],
['CARBAMAZEPINE','CARBAMAZEPINE','200 MG','TAB (TABLET)','ANTIEPILEPTIC'],
['LAMOTRIGINE','LAMOTRIGINE','25 MG','TAB (TABLET)','ANTIEPILEPTIC'],
['PHENYTOIN','PHENYTOIN','100 MG','CAP (CAPSULE)','ANTIEPILEPTIC'],
['DONEPEZIL','DONEPEZIL','5 MG','TAB (TABLET)','NEUROLOGY'],
['MEMANTINE','MEMANTINE','10 MG','TAB (TABLET)','NEUROLOGY'],
['SERTRALINE','SERTRALINE','50 MG','TAB (TABLET)','MENTAL HEALTH'],
['ESCITALOPRAM','ESCITALOPRAM','10 MG','TAB (TABLET)','MENTAL HEALTH'],
['FLUOXETINE','FLUOXETINE','20 MG','CAP (CAPSULE)','MENTAL HEALTH'],
['VENLAFAXINE','VENLAFAXINE','75 MG','CAP (CAPSULE)','MENTAL HEALTH'],
['RISPERIDONE','RISPERIDONE','2 MG','TAB (TABLET)','MENTAL HEALTH'],
['OLANZAPINE','OLANZAPINE','5 MG','TAB (TABLET)','MENTAL HEALTH'],
['QUETIAPINE','QUETIAPINE','25 MG','TAB (TABLET)','MENTAL HEALTH'],
['LITHIUM CARBONATE','LITHIUM CARBONATE','300 MG','TAB (TABLET)','MENTAL HEALTH'],
['CLONAZEPAM','CLONAZEPAM','0.5 MG','TAB (TABLET)','CONTROLLED MEDICINE'],
['ALPRAZOLAM','ALPRAZOLAM','0.25 MG','TAB (TABLET)','CONTROLLED MEDICINE'],
['ZOLPIDEM','ZOLPIDEM','5 MG','TAB (TABLET)','CONTROLLED MEDICINE'],
['LEVODOPA CARBIDOPA','LEVODOPA + CARBIDOPA','COMBINATION','TAB (TABLET)','NEUROLOGY'],
['ROPINIROLE','ROPINIROLE','0.25 MG','TAB (TABLET)','NEUROLOGY'],
['TIMOLOL EYE DROPS','TIMOLOL','0.5%','DROPS','OPHTHALMIC'],
['LATANOPROST EYE DROPS','LATANOPROST','0.005%','DROPS','OPHTHALMIC'],
['BRIMONIDINE EYE DROPS','BRIMONIDINE','0.2%','DROPS','OPHTHALMIC'],
['OFLOXACIN EYE DROPS','OFLOXACIN','0.3%','DROPS','OPHTHALMIC'],
['TOBRAMYCIN EYE DROPS','TOBRAMYCIN','0.3%','DROPS','OPHTHALMIC'],
['CIPROFLOXACIN EAR DROPS','CIPROFLOXACIN','0.3%','DROPS','OTIC'],
['CARBAMIDE PEROXIDE EAR DROPS','CARBAMIDE PEROXIDE','6.5%','DROPS','OTIC'],
['IPRATROPIUM INHALER','IPRATROPIUM','20 MCG/PUFF','INHALER','RESPIRATORY'],
['FORMOTEROL BUDESONIDE','FORMOTEROL + BUDESONIDE','COMBINATION','INHALER','RESPIRATORY'],
['TIOTROPIUM','TIOTROPIUM','18 MCG','INHALER','RESPIRATORY'],
['MONTELUKAST LEVOCETIRIZINE','MONTELUKAST + LEVOCETIRIZINE','COMBINATION','TAB (TABLET)','RESPIRATORY / ALLERGY'],
['THEOPHYLLINE','THEOPHYLLINE','200 MG','TAB (TABLET)','RESPIRATORY'],
['DOXYFYLLINE','DOXOFYLLINE','400 MG','TAB (TABLET)','RESPIRATORY'],
['BROMHEXINE','BROMHEXINE','8 MG','TAB (TABLET)','RESPIRATORY'],
['GUAIFENESIN SYRUP','GUAIFENESIN','SYRUP','SYRUP','RESPIRATORY'],
['BENZONATATE','BENZONATATE','100 MG','CAP (CAPSULE)','RESPIRATORY'],
['OXYMETAZOLINE NASAL SPRAY','OXYMETAZOLINE','0.05%','SPRAY DOSE','NASAL'],
['FLUTICASONE NASAL SPRAY','FLUTICASONE','50 MCG/SPRAY','SPRAY DOSE','NASAL'],
['MOMETASONE NASAL SPRAY','MOMETASONE','50 MCG/SPRAY','SPRAY DOSE','NASAL'],
['OXYTOCIN','OXYTOCIN','10 IU/ML','INJECTION','OBSTETRICS'],
['TRANEXAMIC ACID INJECTION','TRANEXAMIC ACID','500 MG/5 ML','INJECTION','OBSTETRICS / HAEMOSTATIC'],
['MISOPROSTOL','MISOPROSTOL','200 MCG','TAB (TABLET)','OBSTETRICS'],
['METHYLERGOMETRINE','METHYLERGOMETRINE','0.2 MG/ML','INJECTION','OBSTETRICS'],
['PROGESTERONE','PROGESTERONE','200 MG','CAP (CAPSULE)','HORMONAL'],
['MEDROXYPROGESTERONE','MEDROXYPROGESTERONE','10 MG','TAB (TABLET)','HORMONAL'],
['ETHINYLESTRADIOL LEVONORGESTREL','ETHINYLESTRADIOL + LEVONORGESTREL','COMBINATION','TAB (TABLET)','HORMONAL'],
['CLOMIPHENE','CLOMIPHENE CITRATE','50 MG','TAB (TABLET)','FERTILITY'],
['TADALAFIL','TADALAFIL','10 MG','TAB (TABLET)','UROLOGY'],
['SILDENAFIL','SILDENAFIL','50 MG','TAB (TABLET)','UROLOGY'],
['SOLIFENACIN','SOLIFENACIN','5 MG','TAB (TABLET)','UROLOGY'],
['MIRABEGRON','MIRABEGRON','25 MG','TAB (TABLET)','UROLOGY'],
['TAMSULOSIN DUTASTERIDE','TAMSULOSIN + DUTASTERIDE','COMBINATION','CAP (CAPSULE)','UROLOGY'],
['POTASSIUM CITRATE','POTASSIUM CITRATE','SYRUP','SYRUP','UROLOGY'],
['CITRIC ACID SODIUM CITRATE','CITRIC ACID + SODIUM CITRATE','SOLUTION','SOLUTION','UROLOGY'],
['FOSFOMYCIN','FOSFOMYCIN','3 G','SACHET','ANTIBIOTIC'],
['PHENAZOPYRIDINE','PHENAZOPYRIDINE','200 MG','TAB (TABLET)','UROLOGY'],
['METHOTREXATE','METHOTREXATE','2.5 MG','TAB (TABLET)','IMMUNOLOGY'],
['AZATHIOPRINE','AZATHIOPRINE','50 MG','TAB (TABLET)','IMMUNOLOGY'],
['HYDROXYCHLOROQUINE','HYDROXYCHLOROQUINE','200 MG','TAB (TABLET)','RHEUMATOLOGY'],
['SULFASALAZINE','SULFASALAZINE','500 MG','TAB (TABLET)','RHEUMATOLOGY'],
['COLCHICINE','COLCHICINE','0.5 MG','TAB (TABLET)','RHEUMATOLOGY'],
['FEBUXOSTAT','FEBUXOSTAT','40 MG','TAB (TABLET)','GOUT'],
['ALLOPURINOL','ALLOPURINOL','100 MG','TAB (TABLET)','GOUT'],
['TRETINOIN ORAL','TRETINOIN','10 MG','CAP (CAPSULE)','SPECIALIST MEDICINE'],
['CYCLOPHOSPHAMIDE','CYCLOPHOSPHAMIDE','50 MG','TAB (TABLET)','ONCOLOGY'],
['IMATINIB','IMATINIB','400 MG','TAB (TABLET)','ONCOLOGY'],
['LETROZOLE','LETROZOLE','2.5 MG','TAB (TABLET)','ONCOLOGY'],
['TAMOXIFEN','TAMOXIFEN','20 MG','TAB (TABLET)','ONCOLOGY'],
['ONDANSETRON ODT','ONDANSETRON','4 MG','TAB (TABLET)','ANTIEMETIC'],
['FENTANYL','FENTANYL','INJECTION','INJECTION','CONTROLLED MEDICINE'],
['MORPHINE','MORPHINE','INJECTION','INJECTION','CONTROLLED MEDICINE'],
['KETAMINE','KETAMINE','INJECTION','INJECTION','ANAESTHESIA'],
['PROPOFOL','PROPOFOL','INJECTION','INJECTION','ANAESTHESIA'],
['MIDAZOLAM','MIDAZOLAM','INJECTION','INJECTION','ANAESTHESIA'],
['BUPIVACAINE','BUPIVACAINE','0.5%','INJECTION','ANAESTHESIA'],
['LIGNOCAINE ADRENALINE','LIDOCAINE + EPINEPHRINE','COMBINATION','INJECTION','ANAESTHESIA'],
['VECURONIUM','VECURONIUM','INJECTION','INJECTION','ANAESTHESIA'],
['NEOSTIGMINE','NEOSTIGMINE','INJECTION','INJECTION','ANAESTHESIA'],
['FUROSEMIDE INJECTION','FUROSEMIDE','10 MG/ML','INJECTION','DIURETIC'],
['MANNITOL','MANNITOL','20%','INFUSION','OSMOTIC AGENT'],
['ALBUMIN HUMAN','HUMAN ALBUMIN','20%','INFUSION','IV FLUID'],
['POTASSIUM PHOSPHATE','POTASSIUM PHOSPHATE','INJECTION','INJECTION','ELECTROLYTE'],
['SODIUM BICARBONATE','SODIUM BICARBONATE','7.5%','INJECTION','ELECTROLYTE'],
['HEPARIN','HEPARIN SODIUM','5000 IU/ML','INJECTION','ANTICOAGULANT'],
['VITAMIN B COMPLEX','B-COMPLEX VITAMINS','TABLET','TAB (TABLET)','SUPPLEMENT'],
['ELECTROLYTE ORAL SOLUTION','ORAL ELECTROLYTES','SOLUTION','SOLUTION','REHYDRATION'],
['CHLORAMPHENICOL EYE DROPS','CHLORAMPHENICOL','0.5%','DROPS','OPHTHALMIC'],
['ACETAZOLAMIDE','ACETAZOLAMIDE','250 MG','TAB (TABLET)','OPHTHALMIC / DIURETIC'],
['CARBOXYMETHYLCELLULOSE EYE DROPS','CARBOXYMETHYLCELLULOSE','1%','DROPS','OPHTHALMIC'],
['ARTIFICIAL TEARS','LUBRICATING EYE SOLUTION','DROPS','DROPS','OPHTHALMIC'],
['CHLORAMPHENICOL OINTMENT','CHLORAMPHENICOL','1%','OINTMENT','OPHTHALMIC'],
['VACCINE INFLUENZA','INFLUENZA VACCINE','INJECTION','INJECTION','VACCINE'],
['TETANUS TOXOID','TETANUS TOXOID','INJECTION','INJECTION','VACCINE'],
['HEPATITIS B VACCINE','HEPATITIS B VACCINE','INJECTION','INJECTION','VACCINE'],
['RABIES VACCINE','RABIES VACCINE','INJECTION','INJECTION','VACCINE'],
['ANTI-RABIES IMMUNOGLOBULIN','RABIES IMMUNOGLOBULIN','INJECTION','INJECTION','IMMUNOGLOBULIN'],
['HUMAN TETANUS IMMUNOGLOBULIN','TETANUS IMMUNOGLOBULIN','INJECTION','INJECTION','IMMUNOGLOBULIN'],
['CHLORAMPHENICOL','CHLORAMPHENICOL','500 MG','CAP (CAPSULE)','ANTIBIOTIC'],
['NIFUROXAZIDE','NIFUROXAZIDE','200 MG','CAP (CAPSULE)','GASTRO'],
['RACECADOTRIL','RACECADOTRIL','100 MG','CAP (CAPSULE)','GASTRO'],
['PROBIOTIC','LACTOBACILLUS / PROBIOTIC','CAPSULE','CAP (CAPSULE)','GASTRO'],
['LACTASE','LACTASE','TABLET','TAB (TABLET)','DIGESTIVE ENZYME'],
['PANCREATIN','PANCREATIN','CAPSULE','CAP (CAPSULE)','DIGESTIVE ENZYME'],
['URSODEOXYCHOLIC ACID','URSODEOXYCHOLIC ACID','300 MG','CAP (CAPSULE)','HEPATOLOGY'],
['SILYMARIN','SILYMARIN','CAPSULE','CAP (CAPSULE)','HEPATOLOGY'],
['N-ACETYLCYSTEINE','ACETYLCYSTEINE','INJECTION','INJECTION','ANTIDOTE'],
['ACTIVATED CHARCOAL','ACTIVATED CHARCOAL','POWDER','POWDER','ANTIDOTE'],
['FLUMAZENIL','FLUMAZENIL','INJECTION','INJECTION','ANTIDOTE'],
['NALOXONE','NALOXONE','INJECTION','INJECTION','ANTIDOTE'],
['VITAMIN A','RETINOL','CAPSULE','CAP (CAPSULE)','VITAMIN'],
['VITAMIN E','TOCOPHEROL','400 IU','CAP (CAPSULE)','VITAMIN'],
['MAGNESIUM OXIDE','MAGNESIUM OXIDE','400 MG','TAB (TABLET)','SUPPLEMENT'],
['SELENIUM','SELENIUM','TABLET','TAB (TABLET)','SUPPLEMENT'],
['ORAL IRON','FERROUS SULPHATE','TABLET','TAB (TABLET)','HAEMATINIC'],
['FERRIC CARBOXYMALTOSE','FERRIC CARBOXYMALTOSE','INJECTION','INJECTION','HAEMATINIC'],
['DARBEPOETIN ALFA','DARBEPOETIN ALFA','INJECTION','INJECTION','HAEMATINIC'],
['DESMOPRESSIN','DESMOPRESSIN','0.1 MG','TAB (TABLET)','ENDOCRINOLOGY'],
['OCTREOTIDE','OCTREOTIDE','INJECTION','INJECTION','ENDOCRINOLOGY'],
['CABERGOLINE','CABERGOLINE','0.5 MG','TAB (TABLET)','ENDOCRINOLOGY'],
['BROMOCRIPTINE','BROMOCRIPTINE','2.5 MG','TAB (TABLET)','ENDOCRINOLOGY'],
['HUMAN CHORIONIC GONADOTROPIN','HCG','INJECTION','INJECTION','FERTILITY'],
['FOLLITROPIN ALFA','FOLLITROPIN ALFA','INJECTION','INJECTION','FERTILITY'],
['LEVONORGESTREL','LEVONORGESTREL','1.5 MG','TAB (TABLET)','HORMONAL'],
['ULIPRISTAL','ULIPRISTAL ACETATE','30 MG','TAB (TABLET)','HORMONAL'],
['DUTASTERIDE','DUTASTERIDE','0.5 MG','CAP (CAPSULE)','UROLOGY'],
['OXYBUTYNIN','OXYBUTYNIN','5 MG','TAB (TABLET)','UROLOGY'],
['TOLTERODINE','TOLTERODINE','2 MG','TAB (TABLET)','UROLOGY'],
['ACETYLCHOLINESTERASE INHIBITOR','NEOSTIGMINE / RELATED','INJECTION','INJECTION','SPECIALIST MEDICINE'],
['CYCLOSPORINE','CYCLOSPORINE','25 MG','CAP (CAPSULE)','IMMUNOLOGY'],
['TACROLIMUS','TACROLIMUS','0.5 MG','CAP (CAPSULE)','IMMUNOLOGY'],
['MYCOPHENOLATE MOFETIL','MYCOPHENOLATE MOFETIL','500 MG','TAB (TABLET)','IMMUNOLOGY'],
['ADALIMUMAB','ADALIMUMAB','INJECTION','INJECTION','BIOLOGIC'],
['ETANERCEPT','ETANERCEPT','INJECTION','INJECTION','BIOLOGIC'],
['INFLIXIMAB','INFLIXIMAB','INJECTION','INJECTION','BIOLOGIC'],
['OMALIZUMAB','OMALIZUMAB','INJECTION','INJECTION','BIOLOGIC'],
['INSULIN GLARGINE','INSULIN GLARGINE','100 IU/ML','INJECTION','ANTIDIABETIC'],
['INSULIN ASPART','INSULIN ASPART','100 IU/ML','INJECTION','ANTIDIABETIC'],
['INSULIN LISPRO','INSULIN LISPRO','100 IU/ML','INJECTION','ANTIDIABETIC'],
['INSULIN NPH','ISOPHANE INSULIN','100 IU/ML','INJECTION','ANTIDIABETIC'],
['GLUCOSE 25%','DEXTROSE','25%','INJECTION','EMERGENCY MEDICINE'],
['GLUCOSE 50%','DEXTROSE','50%','INJECTION','EMERGENCY MEDICINE'],
['AMLODIPINE TELMISARTAN','AMLODIPINE + TELMISARTAN','COMBINATION','TAB (TABLET)','ANTIHYPERTENSIVE'],
['TELMISARTAN HYDROCHLOROTHIAZIDE','TELMISARTAN + HYDROCHLOROTHIAZIDE','COMBINATION','TAB (TABLET)','ANTIHYPERTENSIVE'],
['LOSARTAN HYDROCHLOROTHIAZIDE','LOSARTAN + HYDROCHLOROTHIAZIDE','COMBINATION','TAB (TABLET)','ANTIHYPERTENSIVE'],
['ATORVASTATIN EZETIMIBE','ATORVASTATIN + EZETIMIBE','COMBINATION','TAB (TABLET)','LIPID LOWERING'],
['ASPIRIN CLOPIDOGREL','ASPIRIN + CLOPIDOGREL','COMBINATION','TAB (TABLET)','ANTIPLATELET'],
['METFORMIN SITAGLIPTIN','METFORMIN + SITAGLIPTIN','COMBINATION','TAB (TABLET)','ANTIDIABETIC'],
['METFORMIN EMPAGLIFLOZIN','METFORMIN + EMPAGLIFLOZIN','COMBINATION','TAB (TABLET)','ANTIDIABETIC'],
['AMOXICILLIN DISPERSIBLE','AMOXICILLIN','250 MG','TAB (TABLET)','ANTIBIOTIC'],
['AMOXICILLIN SUSPENSION','AMOXICILLIN','125 MG/5 ML','SUSPENSION','ANTIBIOTIC'],
['AZITHROMYCIN SUSPENSION','AZITHROMYCIN','200 MG/5 ML','SUSPENSION','ANTIBIOTIC'],
['CEFUROXIME SUSPENSION','CEFUROXIME','125 MG/5 ML','SUSPENSION','ANTIBIOTIC'],
['METRONIDAZOLE SUSPENSION','METRONIDAZOLE','200 MG/5 ML','SUSPENSION','ANTIMICROBIAL'],
['ALBENDAZOLE SUSPENSION','ALBENDAZOLE','200 MG/5 ML','SUSPENSION','ANTHELMINTIC'],
['IBUPROFEN SUSPENSION','IBUPROFEN','100 MG/5 ML','SUSPENSION','NSAID'],
['PARACETAMOL DROPS','PARACETAMOL','100 MG/ML','DROPS','ANALGESIC / ANTIPYRETIC'],
['SALBUTAMOL NEBULIZER','SALBUTAMOL','2.5 MG/2.5 ML','NEBULIZATION','RESPIRATORY'],
['BUDESONIDE NEBULIZER','BUDESONIDE','0.5 MG/2 ML','NEBULIZATION','RESPIRATORY'],
['IPRATROPIUM NEBULIZER','IPRATROPIUM','0.5 MG/2 ML','NEBULIZATION','RESPIRATORY'],
['CEFTRIAXONE','CEFTRIAXONE','500 MG','INJECTION','ANTIBIOTIC'],
['CEFTAZIDIME','CEFTAZIDIME','1 G','INJECTION','ANTIBIOTIC'],
['CEFOPERAZONE SULBACTAM','CEFOPERAZONE + SULBACTAM','INJECTION','INJECTION','ANTIBIOTIC'],
['AMOXICILLIN CLAVULANATE INJECTION','AMOXICILLIN + CLAVULANIC ACID','INJECTION','INJECTION','ANTIBIOTIC'],
['AZTREONAM','AZTREONAM','1 G','INJECTION','ANTIBIOTIC'],
['COLISTIN','COLISTIMETHATE SODIUM','INJECTION','INJECTION','ANTIBIOTIC'],
['ARTESUNATE','ARTESUNATE','INJECTION','INJECTION','ANTIMALARIAL'],
['QUININE','QUININE','300 MG','TAB (TABLET)','ANTIMALARIAL'],
['METFORMIN XR','METFORMIN','500 MG XR','TAB (TABLET)','ANTIDIABETIC'],
['GLIMEPIRIDE METFORMIN','GLIMEPIRIDE + METFORMIN','COMBINATION','TAB (TABLET)','ANTIDIABETIC'],
['BISACODYL SUPPOSITORY','BISACODYL','10 MG','SUPP (SUPPOSITORY)','LAXATIVE'],
['GLYCERIN SUPPOSITORY','GLYCEROL','SUPPOSITORY','SUPP (SUPPOSITORY)','LAXATIVE'],
['MESNA','MESNA','INJECTION','INJECTION','ONCOLOGY SUPPORT'],
['LEUCOVORIN','CALCIUM FOLINATE','INJECTION','INJECTION','ONCOLOGY SUPPORT'],
['FILGRASTIM','FILGRASTIM','INJECTION','INJECTION','ONCOLOGY SUPPORT'],
['PACLITAXEL','PACLITAXEL','INJECTION','INJECTION','ONCOLOGY'],
['CISPLATIN','CISPLATIN','INJECTION','INJECTION','ONCOLOGY'],
['DOXORUBICIN','DOXORUBICIN','INJECTION','INJECTION','ONCOLOGY'],
['RITUXIMAB','RITUXIMAB','INJECTION','INJECTION','BIOLOGIC / ONCOLOGY'],
['PREDNISOLONE EYE DROPS','PREDNISOLONE ACETATE','1%','DROPS','OPHTHALMIC'],
['DEXAMETHASONE EYE DROPS','DEXAMETHASONE','0.1%','DROPS','OPHTHALMIC'],
['CYCLOPENTOLATE EYE DROPS','CYCLOPENTOLATE','1%','DROPS','OPHTHALMIC'],
['TROPICAMIDE EYE DROPS','TROPICAMIDE','1%','DROPS','OPHTHALMIC'],
['PHENYLEPHRINE EYE DROPS','PHENYLEPHRINE','2.5%','DROPS','OPHTHALMIC'],
['EAR DROPS COMBINATION','ANTIBIOTIC + CORTICOSTEROID','DROPS','DROPS','OTIC'],
['SODIUM HYALURONATE EYE DROPS','SODIUM HYALURONATE','DROPS','DROPS','OPHTHALMIC'],
['PAPAVERINE','PAPAVERINE','INJECTION','INJECTION','SPECIALIST MEDICINE'],
['DOPAMINE','DOPAMINE','INJECTION','INJECTION','EMERGENCY MEDICINE'],
['DOBUTAMINE','DOBUTAMINE','INJECTION','INJECTION','EMERGENCY MEDICINE'],
['NORADRENALINE','NOREPINEPHRINE','INJECTION','INJECTION','EMERGENCY MEDICINE'],
['PHENYLEPHRINE INJECTION','PHENYLEPHRINE','INJECTION','INJECTION','EMERGENCY MEDICINE'],
['VASOPRESSIN','VASOPRESSIN','INJECTION','INJECTION','EMERGENCY MEDICINE'],
['MAGNESIUM SULPHATE INJECTION','MAGNESIUM SULPHATE','50%','INJECTION','EMERGENCY MEDICINE'],
['SODIUM CHLORIDE 3%','SODIUM CHLORIDE','3%','INFUSION','IV FLUID'],
['PLASMA-LYTE','BALANCED ELECTROLYTE SOLUTION','INFUSION','INFUSION','IV FLUID'],
['STERILE WATER FOR INJECTION','WATER FOR INJECTION','INJECTION','INJECTION','DILUENT'],
['NORMAL SALINE FLUSH','SODIUM CHLORIDE','0.9%','INJECTION','DILUENT'],
['GLYCEROL','GLYCEROL','SOLUTION','SOLUTION','OTHER'],
['CHLORAL HYDRATE','CHLORAL HYDRATE','SOLUTION','SOLUTION','SPECIALIST MEDICINE'],
['LORAZEPAM','LORAZEPAM','1 MG','TAB (TABLET)','CONTROLLED MEDICINE'],
['DIAZEPAM','DIAZEPAM','5 MG','TAB (TABLET)','CONTROLLED MEDICINE'],
['PHENOBARBITAL','PHENOBARBITAL','30 MG','TAB (TABLET)','CONTROLLED MEDICINE'],
['BUPRENORPHINE','BUPRENORPHINE','TABLET','TAB (TABLET)','CONTROLLED MEDICINE'],
['METHADONE','METHADONE','TABLET','TAB (TABLET)','CONTROLLED MEDICINE'],
['NALTREXONE','NALTREXONE','50 MG','TAB (TABLET)','ADDICTION MEDICINE'],
['DISULFIRAM','DISULFIRAM','250 MG','TAB (TABLET)','ADDICTION MEDICINE'],
['NICOTINE REPLACEMENT','NICOTINE','PATCH','PATCH','OTHER'],
['ALLOPURINOL','ALLOPURINOL','300 MG','TAB (TABLET)','GOUT'],
['FEBUXOSTAT','FEBUXOSTAT','80 MG','TAB (TABLET)','GOUT'],
['DICYCLOMINE','DICYCLOMINE','10 MG','TAB (TABLET)','ANTISPASMODIC'],
['TRIMEBUTINE','TRIMEBUTINE','200 MG','TAB (TABLET)','GASTRO'],
['RABEPRAZOLE DOMPERIDONE','RABEPRAZOLE + DOMPERIDONE','COMBINATION','CAP (CAPSULE)','GASTRO'],
['PANTOPRAZOLE DOMPERIDONE','PANTOPRAZOLE + DOMPERIDONE','COMBINATION','TAB (TABLET)','GASTRO'],
['ALPHA GALACTOSIDASE','ALPHA-GALACTOSIDASE','TABLET','TAB (TABLET)','DIGESTIVE ENZYME'],
['URSODIOL','URSODEOXYCHOLIC ACID','150 MG','TAB (TABLET)','HEPATOLOGY'],
['LACTULOSE SOLUTION','LACTULOSE','SOLUTION','SOLUTION','LAXATIVE'],
['ORAL REHYDRATION SALTS LOW OSMOLARITY','ORAL REHYDRATION SALTS','SACHET','SACHET','REHYDRATION'],
['CHLORAMPHENICOL INJECTION','CHLORAMPHENICOL','INJECTION','INJECTION','ANTIBIOTIC'],
['METOPROLOL SUCCINATE','METOPROLOL SUCCINATE','25 MG','TAB (TABLET)','CARDIAC'],
['IVABRADINE','IVABRADINE','5 MG','TAB (TABLET)','CARDIAC'],
['DIGOXIN INJECTION','DIGOXIN','0.25 MG/ML','INJECTION','CARDIAC'],
['ATORVASTATIN','ATORVASTATIN','40 MG','TAB (TABLET)','LIPID LOWERING'],
['ROSUVASTATIN','ROSUVASTATIN','20 MG','TAB (TABLET)','LIPID LOWERING'],
['PRAVASTATIN','PRAVASTATIN','20 MG','TAB (TABLET)','LIPID LOWERING'],
['FENOFIBRATE','FENOFIBRATE','200 MG','CAP (CAPSULE)','LIPID LOWERING'],
['CLOPIDOGREL','CLOPIDOGREL','150 MG','TAB (TABLET)','ANTIPLATELET'],
['CILOSTAZOL','CILOSTAZOL','100 MG','TAB (TABLET)','VASCULAR'],
['PENTOXIFYLLINE','PENTOXIFYLLINE','400 MG','TAB (TABLET)','VASCULAR'],
['BROMHEXINE SYRUP','BROMHEXINE','SYRUP','SYRUP','RESPIRATORY'],
['LEVOSALBUTAMOL','LEVOSALBUTAMOL','1 MG/ML','NEBULIZATION','RESPIRATORY'],
['RACEcadotril SACHET','RACECADOTRIL','SACHET','SACHET','GASTRO'],
['ZOLMITRIPTAN','ZOLMITRIPTAN','2.5 MG','TAB (TABLET)','MIGRAINE'],
['RIZATRIPTAN','RIZATRIPTAN','10 MG','TAB (TABLET)','MIGRAINE'],
['TOPIRAMATE','TOPIRAMATE','25 MG','TAB (TABLET)','ANTIEPILEPTIC'],
['OXCARBAZEPINE','OXCARBAZEPINE','300 MG','TAB (TABLET)','ANTIEPILEPTIC'],
['PIRACETAM','PIRACETAM','800 MG','TAB (TABLET)','NEUROLOGY'],
['CITICOLINE','CITICOLINE','500 MG','TAB (TABLET)','NEUROLOGY'],
['DONEPEZIL','DONEPEZIL','10 MG','TAB (TABLET)','NEUROLOGY'],
['ESCITALOPRAM','ESCITALOPRAM','5 MG','TAB (TABLET)','MENTAL HEALTH'],
['PAROXETINE','PAROXETINE','20 MG','TAB (TABLET)','MENTAL HEALTH'],
['MIRTAZAPINE','MIRTAZAPINE','15 MG','TAB (TABLET)','MENTAL HEALTH'],
['ARIPIPRAZOLE','ARIPIPRAZOLE','10 MG','TAB (TABLET)','MENTAL HEALTH'],
['HALOPERIDOL','HALOPERIDOL','5 MG','TAB (TABLET)','MENTAL HEALTH'],
['TRIHEXYPHENIDYL','TRIHEXYPHENIDYL','2 MG','TAB (TABLET)','NEUROLOGY'],
['BIPERIDEN','BIPERIDEN','2 MG','TAB (TABLET)','NEUROLOGY'],
['METHYLDOPA','METHYLDOPA','250 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['LABETALOL','LABETALOL','100 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['NIFEDIPINE','NIFEDIPINE','10 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['CLONIDINE','CLONIDINE','0.1 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['PRAZOSIN','PRAZOSIN','1 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['DOXAZOSIN','DOXAZOSIN','2 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['HYDRALAZINE','HYDRALAZINE','25 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['METHIMAZOLE','METHIMAZOLE','5 MG','TAB (TABLET)','THYROID'],
['CALCIUM CARBONATE','CALCIUM CARBONATE','500 MG','TAB (TABLET)','SUPPLEMENT'],
['CHOLECALCIFEROL','CHOLECALCIFEROL','1000 IU','TAB (TABLET)','VITAMIN'],
['ERGOCALCIFEROL','ERGOCALCIFEROL','CAPSULE','CAP (CAPSULE)','VITAMIN'],
['FERRIC AMMONIUM CITRATE','FERRIC AMMONIUM CITRATE','SYRUP','SYRUP','HAEMATINIC'],
['FOLIC ACID','FOLIC ACID','1 MG','TAB (TABLET)','VITAMIN'],
['CYANOCOBALAMIN INJECTION','VITAMIN B12','INJECTION','INJECTION','VITAMIN'],
['HYDROXOCOBALAMIN','HYDROXOCOBALAMIN','INJECTION','INJECTION','VITAMIN'],
['DICLOFENAC GEL','DICLOFENAC','1%','GEL','TOPICAL ANALGESIC'],
['KETOPROFEN GEL','KETOPROFEN','2.5%','GEL','TOPICAL ANALGESIC'],
['CAPSAICIN CREAM','CAPSAICIN','0.025%','CREAM','TOPICAL ANALGESIC'],
['MENTHOL CAMPHOR GEL','MENTHOL + CAMPHOR','GEL','GEL','TOPICAL ANALGESIC'],
['LIDOCAINE PATCH','LIDOCAINE','5%','PATCH','TOPICAL ANALGESIC'],
['METHYL SALICYLATE LINIMENT','METHYL SALICYLATE','LINIMENT','LINIMENT','TOPICAL ANALGESIC'],
['CHLORHEXIDINE MOUTHWASH','CHLORHEXIDINE','0.2%','SOLUTION','ORAL CARE'],
['BENZYDAMINE MOUTHWASH','BENZYDAMINE','0.15%','SOLUTION','ORAL CARE'],
['LIGNOCAINE VISCOUS','LIDOCAINE','2%','SOLUTION','ORAL CARE'],
['FLUCONAZOLE SUSPENSION','FLUCONAZOLE','50 MG/5 ML','SUSPENSION','ANTIFUNGAL'],
['NYSTATIN ORAL SUSPENSION','NYSTATIN','SUSPENSION','SUSPENSION','ANTIFUNGAL'],
['NYSTATIN CREAM','NYSTATIN','CREAM','CREAM','ANTIFUNGAL'],
['MICONAZOLE ORAL GEL','MICONAZOLE','2%','GEL','ANTIFUNGAL'],
['TERBINAFINE CREAM','TERBINAFINE','1%','CREAM','ANTIFUNGAL'],
['ACICLOVIR CREAM','ACICLOVIR','5%','CREAM','ANTIVIRAL'],
['PENCICLOVIR CREAM','PENCICLOVIR','1%','CREAM','ANTIVIRAL'],
['PREDNISOLONE SYRUP','PREDNISOLONE','SYRUP','SYRUP','CORTICOSTEROID'],
['DEXAMETHASONE INJECTION','DEXAMETHASONE','4 MG/ML','INJECTION','CORTICOSTEROID'],
['METHYLPREDNISOLONE INJECTION','METHYLPREDNISOLONE','INJECTION','INJECTION','CORTICOSTEROID'],
['DICLOFENAC SUPPOSITORY','DICLOFENAC','50 MG','SUPP (SUPPOSITORY)','NSAID'],
['PARACETAMOL SUPPOSITORY','PARACETAMOL','125 MG','SUPP (SUPPOSITORY)','ANALGESIC / ANTIPYRETIC'],
['MESALAMINE SUPPOSITORY','MESALAZINE','SUPPOSITORY','SUPP (SUPPOSITORY)','GASTROENTEROLOGY'],
['BUDESONIDE CAPSULE','BUDESONIDE','3 MG','CAP (CAPSULE)','GASTROENTEROLOGY'],
['METHYLDOPA','METHYLDOPA','500 MG','TAB (TABLET)','ANTIHYPERTENSIVE'],
['METHYLERGOMETRINE TABLET','METHYLERGOMETRINE','0.125 MG','TAB (TABLET)','OBSTETRICS'],
['CARBETOCIN','CARBETOCIN','INJECTION','INJECTION','OBSTETRICS'],
['CALCIUM GLUCONATE INJECTION','CALCIUM GLUCONATE','10%','INJECTION','ELECTROLYTE'],
['ANTI-D IMMUNOGLOBULIN','RH(D) IMMUNOGLOBULIN','INJECTION','INJECTION','IMMUNOGLOBULIN'],
['RABIES IMMUNOGLOBULIN','RABIES IMMUNOGLOBULIN','INJECTION','INJECTION','IMMUNOGLOBULIN'],
['HUMAN NORMAL IMMUNOGLOBULIN','HUMAN IMMUNOGLOBULIN','INJECTION','INJECTION','IMMUNOGLOBULIN'],
['DIPHTHERIA TETANUS PERTUSSIS VACCINE','DTP VACCINE','INJECTION','INJECTION','VACCINE'],
['PNEUMOCOCCAL VACCINE','PNEUMOCOCCAL VACCINE','INJECTION','INJECTION','VACCINE'],
['HPV VACCINE','HUMAN PAPILLOMAVIRUS VACCINE','INJECTION','INJECTION','VACCINE'],
['MMR VACCINE','MEASLES MUMPS RUBELLA VACCINE','INJECTION','INJECTION','VACCINE'],
['BCG VACCINE','BCG VACCINE','INJECTION','INJECTION','VACCINE'],
['ROTAVIRUS VACCINE','ROTAVIRUS VACCINE','ORAL SUSPENSION','SOLUTION','VACCINE'],
['POLIO VACCINE','POLIO VACCINE','ORAL / INJECTION','SOLUTION','VACCINE'],
['COVID-19 VACCINE','COVID-19 VACCINE','INJECTION','INJECTION','VACCINE'],
];

$medicineSeedInserted = 0;
$medicineSeedErrors = [];
try {
    // Map available units for the current organization and center.
    $unitMap = [];
    $q = $tenant_pdo->prepare("SELECT id, unit_name FROM master_units WHERE org_id=? AND center_id=? AND status=1");
    $q->execute([$org_id, $center_id]);
    foreach ($q->fetchAll(PDO::FETCH_ASSOC) as $r) {
        $unitMap[strtoupper(trim($r['unit_name']))] = (int)$r['id'];
    }

    // Check duplicates by medicine + strength + generic/salt, and also tolerate
    // databases that have a stricter unique key on medicine_name alone.
    $check = $tenant_pdo->prepare("SELECT id FROM master_medicines WHERE org_id=? AND center_id=? AND UPPER(TRIM(medicine_name))=? AND UPPER(TRIM(COALESCE(strength,'')))=? AND UPPER(TRIM(COALESCE(generic_name,'')))=? LIMIT 1");
    $insert = $tenant_pdo->prepare("INSERT INTO master_medicines (org_id, center_id, medicine_name, generic_name, strength, unit_id, frequency_id, meal_id, default_qty, default_duration_id, manufacturer, category, status, created_by) VALUES (?, ?, ?, ?, ?, ?, NULL, NULL, NULL, NULL, NULL, ?, 1, ?)");

    foreach ($defaultMedicines as $med) {
        [$name, $generic, $strength, $unitName, $category] = $med;
        try {
            $check->execute([$org_id, $center_id, strtoupper(trim($name)), strtoupper(trim($strength)), strtoupper(trim($generic))]);
            if ($check->fetchColumn()) continue;

            $unitId = $unitMap[strtoupper(trim($unitName))] ?? null;
            $insert->execute([$org_id, $center_id, $name, $generic, $strength, $unitId, $category, $created_by ?: null]);
            $medicineSeedInserted++;
        } catch (Throwable $rowError) {
            // One incompatible/duplicate row must not prevent other medicines from seeding.
            $medicineSeedErrors[] = $name . ': ' . $rowError->getMessage();
            error_log('Medicine seed row failed (' . $name . '): ' . $rowError->getMessage());
        }
    }
} catch (Throwable $seedError) {
    $medicineSeedErrors[] = $seedError->getMessage();
    error_log('Medicine default seed error: ' . $seedError->getMessage());
}



// ---------------------------------------------------------

// AJAX QUICK ADD MASTER DATA

// ---------------------------------------------------------

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['ajax_quick_add'])) {

    header('Content-Type: application/json');

    $type = $_POST['type'] ?? '';

    $name = strtoupper(trim($_POST['name'] ?? ''));



    if ($name === '') {

        echo json_encode(['success' => false, 'message' => 'Name cannot be empty.']);

        exit;

    }



    try {

        $table = '';

        $col = '';

        if ($type === 'unit') { $table = 'master_units'; $col = 'unit_name'; }

        elseif ($type === 'frequency') { $table = 'frequency_master'; $col = 'frequency_name'; }

        elseif ($type === 'meal') { $table = 'master_meals'; $col = 'meal_name'; }

        elseif ($type === 'duration') { $table = 'master_durations'; $col = 'duration_name'; }

        else { throw new Exception("Invalid master type."); }



        $stmt = $tenant_pdo->prepare("INSERT INTO {$table} (org_id, center_id, {$col}, status, created_by) VALUES (?, ?, ?, 1, ?)");

        $stmt->execute([$org_id, $center_id, $name, $created_by ?: null]);

        $new_id = $tenant_pdo->lastInsertId();



        echo json_encode(['success' => true, 'id' => $new_id, 'name' => $name, 'type' => $type]);

    } catch (Exception $e) {

        echo json_encode(['success' => false, 'message' => 'Database Error: ' . $e->getMessage()]);

    }

    exit;

}



// ---------------------------------------------------------

// AJAX REFRESH DROPDOWNS

// ---------------------------------------------------------

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['ajax_refresh'])) {

    header('Content-Type: application/json');

    $type = $_POST['type'] ?? '';

    $data = [];

    try {

        if ($type === 'unit') {

            $data = $tenant_pdo->query("SELECT id, unit_name as name, status FROM master_units WHERE org_id = $org_id AND center_id = $center_id ORDER BY unit_name ASC")->fetchAll(PDO::FETCH_ASSOC);

        } elseif ($type === 'frequency') {

            $data = $tenant_pdo->query("SELECT id, frequency_name as name, status FROM frequency_master WHERE org_id = $org_id AND center_id = $center_id ORDER BY frequency_name ASC")->fetchAll(PDO::FETCH_ASSOC);

        } elseif ($type === 'meal') {

            $data = $tenant_pdo->query("SELECT id, meal_name as name, status FROM master_meals WHERE org_id = $org_id AND center_id = $center_id ORDER BY meal_name ASC")->fetchAll(PDO::FETCH_ASSOC);

        } elseif ($type === 'duration') {

            $data = $tenant_pdo->query("SELECT id, duration_name as name, status FROM master_durations WHERE org_id = $org_id AND center_id = $center_id ORDER BY duration_name ASC")->fetchAll(PDO::FETCH_ASSOC);

        } else {

            throw new Exception("Invalid master type for refresh.");

        }

        echo json_encode(['success' => true, 'data' => $data]);

    } catch (Exception $e) {

        echo json_encode(['success' => false, 'message' => $e->getMessage()]);

    }

    exit;

}



// ---------------------------------------------------------

// SAVE / UPDATE

// ---------------------------------------------------------

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action_medicine'])) {



    $medicine_name       = strtoupper(trim($_POST['medicine_name'] ?? ''));

    $generic_name        = strtoupper(trim($_POST['generic_name'] ?? ''));

    $strength            = strtoupper(trim($_POST['strength'] ?? ''));

    $unit_id             = (int)($_POST['unit_id'] ?? 0);

    $frequency_id        = (int)($_POST['frequency_id'] ?? 0);

    $meal_id             = (int)($_POST['meal_id'] ?? 0);

    $default_qty         = strtoupper(trim($_POST['default_qty'] ?? ''));

    $default_duration_id = (int)($_POST['default_duration_id'] ?? 0);

    $manufacturer        = strtoupper(trim($_POST['manufacturer'] ?? ''));

    $category            = strtoupper(trim($_POST['category'] ?? ''));

    $status              = isset($_POST['status']) ? 1 : 0;

    $edit_id             = (int)($_POST['edit_id'] ?? 0);



    if ($medicine_name === '') {

        set_flash_err("Medicine Name is required.");
        $_SESSION['medicine_popup'] = ['icon'=>'error', 'title'=>'Required', 'message'=>'Medicine Name is required.'];
        header('Location: master_medicines.php');
        exit;

    } else {

        try {
            // SERVER-SIDE duplicate guard: medicine name must be unique per clinic/center.
            // Editing the same record is allowed.
            $duplicateStmt = $tenant_pdo->prepare("SELECT id FROM master_medicines
                WHERE org_id = ? AND center_id = ?
                  AND UPPER(TRIM(medicine_name)) = ?
                  AND id <> ? LIMIT 1");
            $duplicateStmt->execute([
                $org_id, $center_id, $medicine_name, $edit_id
            ]);
            $duplicateId = $duplicateStmt->fetchColumn();
            if ($duplicateId) {
                $_SESSION['medicine_popup'] = [
                    'icon' => 'error',
                    'title' => 'Already Exists',
                    'message' => 'A medicine with this name already exists. Please edit the existing record instead.'
                ];
                header('Location: master_medicines.php');
                exit;
            }

            if ($edit_id > 0) {

                $stmt = $tenant_pdo->prepare("

                    UPDATE master_medicines

                    SET medicine_name = ?, generic_name = ?, strength = ?, unit_id = ?, frequency_id = ?, meal_id = ?, default_qty = ?, default_duration_id = ?, manufacturer = ?, category = ?, status = ?

                    WHERE id = ? AND org_id = ? AND center_id = ?

                ");

                $stmt->execute([

                    $medicine_name, $generic_name !== '' ? $generic_name : null, $strength !== '' ? $strength : null,

                    $unit_id > 0 ? $unit_id : null, $frequency_id > 0 ? $frequency_id : null, $meal_id > 0 ? $meal_id : null,

                    $default_qty !== '' ? $default_qty : null, $default_duration_id > 0 ? $default_duration_id : null,

                    $manufacturer !== '' ? $manufacturer : null, $category !== '' ? $category : null, $status,

                    $edit_id, $org_id, $center_id

                ]);

                set_flash_msg("Medicine updated successfully.");
                $_SESSION['medicine_popup'] = ['icon'=>'success', 'title'=>'Updated Successfully', 'message'=>'Medicine updated successfully.'];

            } else {

                $stmt = $tenant_pdo->prepare("

                    INSERT INTO master_medicines (org_id, center_id, medicine_name, generic_name, strength, unit_id, frequency_id, meal_id, default_qty, default_duration_id, manufacturer, category, status, created_by)

                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

                ");

                $stmt->execute([

                    $org_id, $center_id, $medicine_name, $generic_name !== '' ? $generic_name : null, $strength !== '' ? $strength : null,

                    $unit_id > 0 ? $unit_id : null, $frequency_id > 0 ? $frequency_id : null, $meal_id > 0 ? $meal_id : null,

                    $default_qty !== '' ? $default_qty : null, $default_duration_id > 0 ? $default_duration_id : null,

                    $manufacturer !== '' ? $manufacturer : null, $category !== '' ? $category : null, $status, $created_by ?: null

                ]);

                set_flash_msg("Medicine added successfully.");
                $_SESSION['medicine_popup'] = ['icon'=>'success', 'title'=>'Added Successfully', 'message'=>'Medicine added successfully.'];

            }

            header("Location: master_medicines.php");

            exit;

        } catch (PDOException $e) {

            set_flash_err("Database Error: " . $e->getMessage());
            $_SESSION['medicine_popup'] = ['icon'=>'error', 'title'=>'Database Error', 'message'=>$e->getMessage()];

        }

    }

}



// ---------------------------------------------------------

// TOGGLE STATUS

// ---------------------------------------------------------

if (isset($_GET['toggle_status'])) {

    $id = (int)$_GET['toggle_status'];

    $st = ((int)($_GET['st'] ?? 1) === 1) ? 0 : 1;

    $tenant_pdo->prepare("UPDATE master_medicines SET status = ? WHERE id = ? AND org_id = ? AND center_id = ?")->execute([$st, $id, $org_id, $center_id]);

    header("Location: master_medicines.php");

    exit;

}



// ---------------------------------------------------------

// MASTER DROPDOWNS

// ---------------------------------------------------------

$units = $tenant_pdo->query("SELECT id, unit_name, status FROM master_units WHERE org_id = $org_id AND center_id = $center_id ORDER BY unit_name ASC")->fetchAll() ?: [];

$frequencies = $tenant_pdo->query("SELECT id, frequency_name, status FROM frequency_master WHERE org_id = $org_id AND center_id = $center_id ORDER BY frequency_name ASC")->fetchAll() ?: [];

$meals = $tenant_pdo->query("SELECT id, meal_name, status FROM master_meals WHERE org_id = $org_id AND center_id = $center_id ORDER BY meal_name ASC")->fetchAll() ?: [];

$durations = $tenant_pdo->query("SELECT id, duration_name, status FROM master_durations WHERE org_id = $org_id AND center_id = $center_id ORDER BY duration_name ASC")->fetchAll() ?: [];



// ---------------------------------------------------------

// LIST

// ---------------------------------------------------------

$medicinesStmt = $tenant_pdo->prepare("

    SELECT m.*, u.unit_name, f.frequency_name, ml.meal_name, d.duration_name

    FROM master_medicines m

    LEFT JOIN master_units u ON u.id = m.unit_id AND u.org_id = m.org_id AND u.center_id = m.center_id

    LEFT JOIN frequency_master f ON f.id = m.frequency_id AND f.org_id = m.org_id AND f.center_id = m.center_id

    LEFT JOIN master_meals ml ON ml.id = m.meal_id AND ml.org_id = m.org_id AND ml.center_id = m.center_id

    LEFT JOIN master_durations d ON d.id = m.default_duration_id AND d.org_id = m.org_id AND d.center_id = m.center_id

    WHERE m.org_id = ? AND m.center_id = ?

    ORDER BY m.id DESC

");

$medicinesStmt->execute([$org_id, $center_id]);

$medicines = $medicinesStmt->fetchAll() ?: [];



$medicinePopup = $_SESSION['medicine_popup'] ?? null;
unset($_SESSION['medicine_popup']);

require_once __DIR__ . '/layout_header.php';

?>



<div class="row g-2">

    <!-- FORM -->

    <div class="col-lg-4">

        <div class="card border shadow-sm">

            <div class="card-header bg-white py-2 px-2 border-bottom">

                <span class="fw-bold small text-dark" id="formTitle">

                    <i class="bi bi-capsule text-primary me-1"></i> ADD MEDICINE

                </span>

            </div>

            <div class="card-body p-2">

                <form method="POST" action="">

                    <input type="hidden" name="action_medicine" value="1">

                    <input type="hidden" name="edit_id" id="edit_id" value="0">



                    <div class="row g-1 mb-2">

                        <div class="col-md-8">

                            <label class="form-label mb-0" style="font-size: 10px; font-weight: 600; color: #6c757d;">MEDICINE NAME *</label>

                            <input type="text" name="medicine_name" id="medicine_name" class="form-control form-control-sm text-uppercase" maxlength="200" required autofocus>

                        </div>

                        <div class="col-md-4">

                            <label class="form-label mb-0" style="font-size: 10px; font-weight: 600; color: #6c757d;">STRENGTH</label>

                            <input type="text" name="strength" id="strength" class="form-control form-control-sm text-uppercase" maxlength="100">

                        </div>

                    </div>



                    <div class="row g-1 mb-2">

                        <div class="col-md-6">

                            <label class="form-label mb-0" style="font-size: 10px; font-weight: 600; color: #6c757d;">GENERIC / SALT</label>

                            <input type="text" name="generic_name" id="generic_name" class="form-control form-control-sm text-uppercase" maxlength="200">

                        </div>

                        <div class="col-md-6">

                            <label class="form-label mb-0" style="font-size: 10px; font-weight: 600; color: #6c757d;">FREQUENCY</label>

                            <div class="input-group input-group-sm">

                                <select name="frequency_id" id="frequency_id" class="form-select form-select-sm">

                                    <option value="">SELECT</option>

                                    <?php foreach ($frequencies as $f): ?>

                                        <option value="<?= (int)$f['id'] ?>" <?= (int)$f['status'] !== 1 ? 'class="text-muted"' : '' ?>><?= htmlspecialchars($f['frequency_name']) ?></option>

                                    <?php endforeach; ?>

                                </select>

                                <button type="button" class="btn btn-outline-secondary px-2" id="btn_ref_frequency" onclick="refreshDropdown('frequency')" title="Refresh">

                                    <i class="bi bi-arrow-clockwise"></i>

                                </button>

                                <button type="button" class="btn btn-outline-secondary px-2" onclick="openQuickAdd('frequency', 'Add Frequency')" title="Add Frequency">

                                    <i class="bi bi-plus-lg"></i>

                                </button>

                            </div>

                        </div>

                    </div>



                    <div class="row g-1 mb-2">

                        <div class="col-md-6">

                            <label class="form-label mb-0" style="font-size: 10px; font-weight: 600; color: #6c757d;">UNIT / FORM</label>

                            <div class="input-group input-group-sm">

                                <select name="unit_id" id="unit_id" class="form-select form-select-sm">

                                    <option value="">SELECT</option>

                                    <?php foreach ($units as $u): ?>

                                        <option value="<?= (int)$u['id'] ?>" <?= (int)$u['status'] !== 1 ? 'class="text-muted"' : '' ?>><?= htmlspecialchars($u['unit_name']) ?></option>

                                    <?php endforeach; ?>

                                </select>

                                <button type="button" class="btn btn-outline-secondary px-2" id="btn_ref_unit" onclick="refreshDropdown('unit')" title="Refresh">

                                    <i class="bi bi-arrow-clockwise"></i>

                                </button>

                                <button type="button" class="btn btn-outline-secondary px-2" onclick="openQuickAdd('unit', 'Add Unit / Form')" title="Add Unit">

                                    <i class="bi bi-plus-lg"></i>

                                </button>

                            </div>

                        </div>

                        <div class="col-md-6">

                            <label class="form-label mb-0" style="font-size: 10px; font-weight: 600; color: #6c757d;">MEAL TIMING</label>

                            <div class="input-group input-group-sm">

                                <select name="meal_id" id="meal_id" class="form-select form-select-sm">

                                    <option value="">SELECT</option>

                                    <?php foreach ($meals as $ml): ?>

                                        <option value="<?= (int)$ml['id'] ?>"><?= htmlspecialchars($ml['meal_name']) ?></option>

                                    <?php endforeach; ?>

                                </select>

                                <button type="button" class="btn btn-outline-secondary px-2" id="btn_ref_meal" onclick="refreshDropdown('meal')" title="Refresh">

                                    <i class="bi bi-arrow-clockwise"></i>

                                </button>

                                <button type="button" class="btn btn-outline-secondary px-2" onclick="openQuickAdd('meal', 'Add Meal Timing')" title="Add Meal Timing">

                                    <i class="bi bi-plus-lg"></i>

                                </button>

                            </div>

                        </div>

                    </div>



                    <div class="row g-1 mb-2">

                        <div class="col-md-6">

                            <label class="form-label mb-0" style="font-size: 10px; font-weight: 600; color: #6c757d;">DEFAULT QTY</label>

                            <input type="text" name="default_qty" id="default_qty" class="form-control form-control-sm text-uppercase" placeholder="E.G. 1" maxlength="50">

                        </div>

                        <div class="col-md-6">

                            <label class="form-label mb-0" style="font-size: 10px; font-weight: 600; color: #6c757d;">DURATION</label>

                            <div class="input-group input-group-sm">

                                <select name="default_duration_id" id="default_duration_id" class="form-select form-select-sm">

                                    <option value="">SELECT</option>

                                    <?php foreach ($durations as $d): ?>

                                        <option value="<?= (int)$d['id'] ?>"><?= htmlspecialchars($d['duration_name']) ?></option>

                                    <?php endforeach; ?>

                                </select>

                                <button type="button" class="btn btn-outline-secondary px-2" id="btn_ref_duration" onclick="refreshDropdown('duration')" title="Refresh">

                                    <i class="bi bi-arrow-clockwise"></i>

                                </button>

                                <button type="button" class="btn btn-outline-secondary px-2" onclick="openQuickAdd('duration', 'Add Duration')" title="Add Duration">

                                    <i class="bi bi-plus-lg"></i>

                                </button>

                            </div>

                        </div>

                    </div>



                    <div class="row g-1 mb-3">

                        <div class="col-md-7">

                            <label class="form-label mb-0" style="font-size: 10px; font-weight: 600; color: #6c757d;">MANUFACTURER</label>

                            <input type="text" name="manufacturer" id="manufacturer" class="form-control form-control-sm text-uppercase" maxlength="200">

                        </div>

                        <div class="col-md-5">

                            <label class="form-label mb-0" style="font-size: 10px; font-weight: 600; color: #6c757d;">CATEGORY</label>

                            <input type="text" name="category" id="category" class="form-control form-control-sm text-uppercase" maxlength="100">

                        </div>

                    </div>



                    <div class="d-flex justify-content-between align-items-center border-top pt-2 mt-1">

                        <div class="form-check form-switch mb-0">

                            <input class="form-check-input" type="checkbox" name="status" id="status" checked>

                            <label class="form-check-label mb-0" style="font-size: 10px; font-weight: 600; color: #6c757d;" for="status">ACTIVE</label>

                        </div>

                        <div class="d-flex gap-1">

                            <button type="reset" class="btn btn-light btn-sm border px-3 py-1" style="font-size: 11px; font-weight: 600;" onclick="resetForm()">RESET</button>

                            <button type="submit" class="btn btn-primary btn-sm px-3 py-1" style="font-size: 11px; font-weight: 600;" id="btnSubmit">SAVE</button>

                        </div>

                    </div>

                </form>

            </div>

        </div>

    </div>



    <!-- LIST -->

    <div class="col-lg-8">

        <div class="card border shadow-sm">

            <div class="card-header bg-white py-2 px-3 border-bottom d-flex justify-content-between align-items-center">

                <span class="fw-bold small text-dark">

                    <i class="bi bi-list-task text-primary me-1"></i> MEDICINES LIST

                </span>



                <div class="d-flex align-items-center gap-2">

                    <div class="input-group input-group-sm" style="width: 250px;">

                        <span class="input-group-text bg-light border-end-0"><i class="bi bi-search text-muted"></i></span>

                        <input type="text" id="liveSearch" class="form-control border-start-0 ps-0" placeholder="Type to search..." onkeyup="filterTable()">

                    </div>

                    <span class="badge bg-light text-secondary border px-2 py-1">

                        <span id="recordCount"><?= count($medicines) ?></span> RECORDS

                    </span>

                </div>

            </div>



            <div class="card-body p-0">

                <div class="table-responsive" style="max-height:75vh; overflow-y:auto;">

                    <table class="table table-sm table-hover align-middle mb-0" style="font-size:11px;" id="medicinesTable">

                        <thead class="table-light sticky-top" style="z-index: 1;">

                            <tr>

                                <th class="ps-2 text-muted" style="width:40px;">#</th>

                                <th class="text-muted">MEDICINE</th>

                                <th class="text-muted">SALT</th>

                                <th class="text-muted">STRENGTH</th>

                                <th class="text-muted">UNIT</th>

                                <th class="text-muted">FREQ</th>

                                <th class="text-muted">MEAL</th>

                                <th class="text-muted">QTY</th>

                                <th class="text-muted">DUR</th>

                                <th class="text-muted text-center">STATUS</th>

                                <th class="text-end pe-2 text-muted">ACT</th>

                            </tr>

                        </thead>

                        <tbody id="tableBody">

                        <?php if (empty($medicines)): ?>

                            <tr id="noRecordsRow">

                                <td colspan="11" class="text-center py-3 text-muted">NO MEDICINES FOUND.</td>

                            </tr>

                        <?php else: ?>

                            <?php foreach ($medicines as $m): ?>

                                <?php $is_act = (int)$m['status'] === 1; ?>

                                <tr>

                                    <td class="ps-2 font-monospace text-muted">#<?= (int)$m['id'] ?></td>

                                    <td><div class="fw-bold text-dark text-uppercase"><?= htmlspecialchars($m['medicine_name']) ?></div></td>

                                    <td class="text-uppercase text-secondary"><?= htmlspecialchars($m['generic_name'] ?? '') ?: '-' ?></td>

                                    <td class="font-monospace text-secondary"><?= htmlspecialchars($m['strength'] ?? '') ?: '-' ?></td>

                                    <td class="text-uppercase text-secondary"><?= htmlspecialchars($m['unit_name'] ?? '') ?: '-' ?></td>

                                    <td class="text-uppercase text-secondary"><?= htmlspecialchars($m['frequency_name'] ?? '') ?: '-' ?></td>

                                    <td class="text-uppercase text-secondary"><?= htmlspecialchars($m['meal_name'] ?? '') ?: '-' ?></td>

                                    <td class="text-secondary"><?= htmlspecialchars($m['default_qty'] ?? '') ?: '-' ?></td>

                                    <td class="text-uppercase text-secondary"><?= htmlspecialchars($m['duration_name'] ?? '') ?: '-' ?></td>

                                    <td class="text-center">

                                        <a href="?toggle_status=<?= (int)$m['id'] ?>&st=<?= $is_act ? 1 : 0 ?>" class="badge text-decoration-none <?= $is_act ? 'bg-success-subtle text-success border border-success' : 'bg-danger-subtle text-danger border border-danger' ?>">

                                            <?= $is_act ? 'ACT' : 'INACT' ?>

                                        </a>

                                    </td>

                                    <td class="text-end pe-2">

                                        <button type="button" class="btn btn-outline-primary btn-sm py-0 px-1" onclick='editRow(<?= json_encode($m, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP) ?>)' title="EDIT">

                                            <i class="bi bi-pencil" style="font-size: 10px;"></i>

                                        </button>

                                    </td>

                                </tr>

                            <?php endforeach; ?>

                        <?php endif; ?>

                        </tbody>

                    </table>

                </div>

            </div>

        </div>

    </div>

</div>



<!-- AJAX QUICK ADD MODAL -->

<div class="modal fade" id="quickAddModal" tabindex="-1" aria-hidden="true">

    <div class="modal-dialog modal-sm modal-dialog-centered">

        <div class="modal-content border-0 shadow">

            <div class="modal-header bg-light py-2 px-3">

                <h6 class="modal-title fw-bold text-primary" id="quickAddTitle">Add New</h6>

                <button type="button" class="btn-close btn-sm" data-bs-dismiss="modal" aria-label="Close"></button>

            </div>

            <div class="modal-body p-3">

                <form id="quickAddForm" onsubmit="saveQuickAdd(event)">

                    <input type="hidden" id="qa_type">

                    <div class="mb-3">

                        <label class="form-label mb-1" style="font-size: 11px; font-weight: 600; color: #6c757d;">NAME / TITLE *</label>

                        <input type="text" id="qa_name" class="form-control form-control-sm text-uppercase" required>

                    </div>

                    <div class="text-end border-top pt-2">

                        <button type="button" class="btn btn-light btn-sm px-3 fw-semibold border" data-bs-dismiss="modal">CANCEL</button>

                        <button type="submit" class="btn btn-primary btn-sm px-4 fw-semibold" id="qa_btn">SAVE</button>

                    </div>

                </form>

            </div>

        </div>

    </div>

</div>



<script>

// SweetAlert-style fallback popup (works even when SweetAlert2 is not loaded)
function medicinePopup(icon, title, message, autoClose=false) {
    if (typeof Swal !== 'undefined') {
        Swal.fire({icon, title, text: message, timer: autoClose ? 5000 : undefined, showConfirmButton: !autoClose, confirmButtonText:'OK'});
        return;
    }
    let old=document.getElementById('medicinePopupOverlay'); if(old) old.remove();
    const overlay=document.createElement('div'); overlay.id='medicinePopupOverlay';
    overlay.style='position:fixed;inset:0;background:#0006;z-index:20000;display:flex;align-items:center;justify-content:center;';
    const color=icon==='success'?'#16a34a':'#dc2626';
    overlay.innerHTML=`<div style="background:#fff;width:min(340px,92vw);padding:22px 24px;border-radius:16px;text-align:center;box-shadow:0 15px 50px #0003;font-family:Arial,sans-serif"><div style="margin:auto auto 12px;width:46px;height:46px;border:3px solid ${color};color:${color};border-radius:50%;font-size:30px;line-height:40px">${icon==='success'?'✓':'!'}</div><div style="font-size:20px;font-weight:700;margin-bottom:8px">${title}</div><div style="font-size:14px;color:#64748b;margin-bottom:16px;overflow-wrap:anywhere"></div><button id="medicinePopupOk" style="${autoClose?'display:none;':''}background:#2563eb;color:white;border:0;border-radius:8px;padding:10px 28px;font-weight:600">OK</button>${autoClose?'<div style="height:3px;background:#e5e7eb;margin-top:18px"><div id="medicinePopupProgress" style="height:3px;background:#16a34a;width:100%"></div></div>':''}</div>`;
    overlay.querySelector('div div:nth-child(3)').textContent=message; document.body.appendChild(overlay);
    const close=()=>overlay.remove(); const ok=overlay.querySelector('#medicinePopupOk'); if(ok)ok.onclick=close;
    if(autoClose){const bar=overlay.querySelector('#medicinePopupProgress');bar.style.transition='width 5s linear';requestAnimationFrame(()=>bar.style.width='0%');setTimeout(close,5000);}
}
// Display server-side add/update/error/duplicate messages after redirect.
const serverMedicinePopup = <?php echo json_encode($medicinePopup, JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP); ?>;
if (serverMedicinePopup && serverMedicinePopup.message) {
    window.addEventListener('DOMContentLoaded', () => medicinePopup(
        serverMedicinePopup.icon || 'success',
        serverMedicinePopup.title || 'Notice',
        serverMedicinePopup.message,
        (serverMedicinePopup.icon || '') === 'success'
    ));
}

// Show whether default catalogue rows were actually added (helps diagnose schema/constraint issues).
const seededMedicineCount = <?php echo (int)$medicineSeedInserted; ?>;
const medicineSeedErrorCount = <?php echo count($medicineSeedErrors); ?>;
if (seededMedicineCount > 0) {
    window.addEventListener('DOMContentLoaded', () => medicinePopup('success', 'Catalogue Added', seededMedicineCount + ' default medicine entries added.', true));
} else if (medicineSeedErrorCount > 0) {
    window.addEventListener('DOMContentLoaded', () => medicinePopup('error', 'Catalogue Import Issue', 'No new entries were added. Check PHP error log; ' + medicineSeedErrorCount + ' row(s) could not be imported.', false));
}
const medicineForm=document.querySelector('form[method="POST"]');
const medicineInput=document.getElementById('medicine_name');
const strengthInput=document.getElementById('strength');
const genericInput=document.getElementById('generic_name');
const medicineSubmit=document.getElementById('btnSubmit');
const existingMedicineKeys = <?php echo json_encode(array_map(function($m){return [strtoupper(trim($m['medicine_name'])),strtoupper(trim($m['strength'] ?? '')),strtoupper(trim($m['generic_name'] ?? '')),(int)$m['id']];}, $medicines), JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP); ?>;
let duplicateMedicine=false;
function checkMedicineDuplicate(){
  if(!medicineInput || !medicineSubmit)return;
  const n=medicineInput.value.trim().toUpperCase(), edit=parseInt(document.getElementById('edit_id')?.value||'0');
  // Match by name immediately, as requested; exclude the current row while editing.
  duplicateMedicine=!!n && existingMedicineKeys.some(x=>x[0]===n && x[3]!==edit);
  let msg=document.getElementById('medicineDuplicateMsg');
  if(!msg){msg=document.createElement('div');msg.id='medicineDuplicateMsg';msg.style='font-size:11px;margin-top:4px;font-weight:600';medicineInput.parentNode.appendChild(msg);}
  msg.textContent=duplicateMedicine?'Already exists: this medicine name is already in the list. Edit the existing record instead.':'';
  msg.style.color='#dc2626'; medicineInput.style.borderColor=duplicateMedicine?'#dc2626':'';
  medicineSubmit.disabled=duplicateMedicine;
}
[medicineInput,strengthInput,genericInput].forEach(el=>el&&el.addEventListener('input',checkMedicineDuplicate));
if(medicineForm) medicineForm.addEventListener('submit',e=>{checkMedicineDuplicate();if(duplicateMedicine){e.preventDefault();medicinePopup('error','Already Exists','This medicine name is already present. Please edit the existing record instead.',false);}});
// Flash messages captured after layout header may have consumed them; PHP session values are checked below.

// ---------- EXISTING FUNCTIONS ----------

function editRow(d) {

    document.getElementById('edit_id').value = d.id || '0';

    document.getElementById('medicine_name').value = d.medicine_name || '';

    document.getElementById('generic_name').value = d.generic_name || '';

    document.getElementById('strength').value = d.strength || '';

    document.getElementById('unit_id').value = d.unit_id || '';

    document.getElementById('frequency_id').value = d.frequency_id || '';

    document.getElementById('meal_id').value = d.meal_id || '';

    document.getElementById('default_qty').value = d.default_qty || '';

    document.getElementById('default_duration_id').value = d.default_duration_id || '';

    document.getElementById('manufacturer').value = d.manufacturer || '';

    document.getElementById('category').value = d.category || '';

    document.getElementById('status').checked = (parseInt(d.status) === 1);



    document.getElementById('formTitle').innerHTML = '<i class="bi bi-pencil-square text-warning me-1"></i> EDIT MEDICINE';

    document.getElementById('btnSubmit').innerText = 'UPDATE';

    document.getElementById('medicine_name').focus();

}



function resetForm() {

    document.getElementById('edit_id').value = '0';

    document.getElementById('formTitle').innerHTML = '<i class="bi bi-capsule text-primary me-1"></i> ADD MEDICINE';

    document.getElementById('btnSubmit').innerText = 'SAVE';

    document.getElementById('status').checked = true;

    setTimeout(() => { document.getElementById('medicine_name').focus(); checkMedicineDuplicate(); }, 10);

}



function filterTable() {

    const input = document.getElementById('liveSearch');

    const filter = input.value.toUpperCase();

    const tbody = document.getElementById('tableBody');

    const tr = tbody.getElementsByTagName('tr');

    let visibleCount = 0;



    for (let i = 0; i < tr.length; i++) {

        if (tr[i].id === 'noRecordsRow') continue;



        const textValue = tr[i].textContent || tr[i].innerText;

        if (textValue.toUpperCase().indexOf(filter) > -1) {

            tr[i].style.display = '';

            visibleCount++;

        } else {

            tr[i].style.display = 'none';

        }

    }

    document.getElementById('recordCount').innerText = visibleCount;

}



// ---------- QUICK ADD & REFRESH FUNCTIONS ----------

let qaModalInstance = null;



document.addEventListener("DOMContentLoaded", function() {

    qaModalInstance = new bootstrap.Modal(document.getElementById('quickAddModal'));

});



function openQuickAdd(type, title) {

    document.getElementById('qa_type').value = type;

    document.getElementById('quickAddTitle').innerText = title;

    document.getElementById('qa_name').value = '';

    qaModalInstance.show();

    setTimeout(() => { document.getElementById('qa_name').focus(); }, 500);

}



async function saveQuickAdd(e) {

    e.preventDefault();

    const type = document.getElementById('qa_type').value;

    const name = document.getElementById('qa_name').value;

    const btn  = document.getElementById('qa_btn');



    btn.disabled = true;

    btn.innerHTML = '<span class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span> SAVING...';



    try {

        const formData = new FormData();

        formData.append('ajax_quick_add', '1');

        formData.append('type', type);

        formData.append('name', name);



        const res = await fetch('', { method: 'POST', body: formData });

        const data = await res.json();



        if (data.success) {

            qaModalInstance.hide();

            await refreshDropdown(type); // Auto refresh the list



            // Auto select newly added item

            let selectId = type + '_id';

            if (type === 'duration') selectId = 'default_duration_id';

            document.getElementById(selectId).value = data.id;



            if (typeof Swal !== 'undefined') {

                Swal.fire({

                    icon: 'success',

                    title: 'Added Successfully',

                    text: data.name,

                    timer: 1500,

                    showConfirmButton: false,

                    toast: true,

                    position: 'top-end'

                });

            }

        } else {

            if (typeof Swal !== 'undefined') Swal.fire({ icon: 'error', title: 'Oops...', text: data.message });

        }

    } catch (error) {

        if (typeof Swal !== 'undefined') Swal.fire({ icon: 'error', title: 'Error', text: 'Something went wrong.' });

        console.error(error);

    } finally {

        btn.disabled = false;

        btn.innerText = 'SAVE';

    }

}



async function refreshDropdown(type) {

    const btnId = 'btn_ref_' + type;

    const btn = document.getElementById(btnId);

    if(btn) {

        btn.disabled = true;

        btn.innerHTML = '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true" style="width: 0.8rem; height: 0.8rem;"></span>';

    }



    try {

        const formData = new FormData();

        formData.append('ajax_refresh', '1');

        formData.append('type', type);



        const res = await fetch('', { method: 'POST', body: formData });

        const result = await res.json();



        if (result.success) {

            let selectId = type + '_id';

            if (type === 'duration') selectId = 'default_duration_id';



            const selectEl = document.getElementById(selectId);

            const currentVal = selectEl.value; // Store selected value



            // Clear items

            selectEl.innerHTML = '<option value="">SELECT</option>';



            // Repopulate

            result.data.forEach(item => {

                const opt = document.createElement('option');

                opt.value = item.id;

                opt.textContent = item.name + (parseInt(item.status) !== 1 ? ' (INACTIVE)' : '');

                if (parseInt(item.status) !== 1) opt.className = 'text-muted';

                selectEl.appendChild(opt);

            });



            // Restore selection if item still exists

            selectEl.value = currentVal;



            if (typeof Swal !== 'undefined' && event && event.type === 'click') {

                Swal.fire({ icon: 'success', title: 'Refreshed', timer: 1000, showConfirmButton: false, toast: true, position: 'top-end' });

            }

        } else {

            if (typeof Swal !== 'undefined') Swal.fire({ icon: 'error', title: 'Error', text: result.message });

        }

    } catch(e) {

        console.error(e);

    } finally {

        if(btn) {

            btn.disabled = false;

            btn.innerHTML = '<i class="bi bi-arrow-clockwise"></i>';

        }

    }

}

</script>



<?php require_once __DIR__ . '/layout_footer.php'; ?>
